[package]
name = "jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
argon2 = { version = "0.6.0-rc.0", features = ["password-hash", "std"] }